### ISSUE TITLE
guide_colbar title property adjustment

### ISSUE THREAD

**Issue by Breeze-Hu** [teunbrand/legendry#37]
Dear Teun van den Brand,

Can `guide_colbar` add `title.position` and `title.hjust` parameters to adjust the title position of the colorbar like guide_colorbar in ggplot?

The following code adjusts the position of the colorbar, the position of the colorbar header (**top and hjust**), but does not set the out-of-range triangle shape:
```
library(tidyverse)
library(legendry)
library(terra)

m <- matrix(1:25, nrow=5, ncol=5)
rm <- rast(m)

# from a "xyz" data.frame
data <- as.data.frame(rm, xy=TRUE)
bwr_colors <- c("blue", "white", "red")

ggplot(data = data,aes(x = x,y = y,fill = lyr.1)) +
  geom_tile() + 
  scale_fill_gradientn(
    colors = bwr_colors, 
    na.value = NA,
    limits = c(5, 20), oob = scales::oob_squish,
    guide = guide_colorbar(#shape = "triangle",
                         title.position = "top",
                         title.hjust = 0.5)) +
  theme_bw()+
  theme(
    legend.position = "bottom",             
    legend.key.width = unit(2, "cm"),       
    legend.key.height = unit(0.4, "cm"))
```
![image](https://github.com/user-attachments/assets/139ea88a-1230-4aa8-b09d-abadb2979d3c)

It's more elegant to use `guide_colbar` when setting the triangle shape, but it doesn't seem to be possible to set the title position of the colorbar: 
```
ggplot(data = data,aes(x = x,y = y,fill = lyr.1)) +
  geom_tile() + 
  scale_fill_gradientn(
    colors = bwr_colors, 
    na.value = NA,
    limits = c(5, 20), oob = scales::oob_squish,
    guide = guide_colbar(shape = "triangle")
                         # title.position = "top",
                         # title.hjust = 0.5)
  ) +
  theme_bw()+
  theme(
    legend.position = "bottom",             
    legend.key.width = unit(2, "cm"),       
    legend.key.height = unit(0.4, "cm"))     
)
```
![image](https://github.com/user-attachments/assets/bf7e7d1a-8d61-45a4-a70c-ca8ea0dd47c1)

If settings similar to the above are made, an error is prompted: 
```
`Error in guide_colbar(shape = "triangle", title.position = "top", title.hjust = 0.5) : 
  unused arguments (title.position = "top", title.hjust = 0.5)'
```

Best regards
Hu

**Comment by teunbrand** [comment]
Hi Hu, thank you for the report! 

At the risk of sounding slightly rude: no, absolutely not.

The reason is that ggplot2 has removed these arguments and they only still work because of a backward compatibility mechanism. The legendry package is not beholden to ggplot2's backward compatibility, so it will not use the old deprecated arguments.

The "proper" way of setting such customisations is via the `guide_colourbar(theme)` argument (see [blog](https://www.tidyverse.org/blog/2024/02/ggplot2-3-5-0-legends/#styling)), and this works the same way in legendry. You could use `theme_guide()` to be slightly more terse. I could add an example of this, but it really isn't any different than ggplot2.

``` r
library(tidyverse)
library(legendry)
library(terra)

m <- matrix(1:25, nrow=5, ncol=5)
rm <- rast(m)

# from a "xyz" data.frame
data <- as.data.frame(rm, xy=TRUE)
bwr_colors <- c("blue", "white", "red")

ggplot(data = data,aes(x = x,y = y,fill = lyr.1)) +
  geom_tile() + 
  scale_fill_gradientn(
    colors = bwr_colors, 
    na.value = NA,
    limits = c(5, 20), oob = scales::oob_squish,
    guide = guide_colbar(
      theme = theme_guide(
        title.position = "top",
        title = element_text(hjust = 0.5)
      )
    )) +
  theme_bw()+
  theme(
    legend.position = "bottom",             
    legend.key.width = unit(2, "cm"),       
    legend.key.height = unit(0.4, "cm")
  )
```

![](https://i.imgur.com/CQ8wqis.png)

<sup>Created on 2024-12-16 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by Breeze-Hu** [comment]
Perfect! Thank you for your detailed reply. I read what you mentioned carefully and this does work well to unify the various attribute contents of the guide using the theme framework!
Thanks for contributing to the ggplot ecosystem! Packages such as `legendry` and `ggh4x` make plotting much more accessible and convenient!

**Comment by Breeze-Hu** [comment]
Sorry to bother you again. 
is there something problem with the height and width adjustment of the colorbar in the `theme_guide` function provided by `legendry`?
Using `key.width` and `key.height` seems to have no effect. But it is valid to use `theme` instead of `theme_guide` .

See details:
[stackoverflow-question](https://stackoverflow.com/questions/79289871/legendry-and-ggplot-theme-guide-adjustment-of-height-and-width-failure/79289898#79289898)

**Comment by teunbrand** [comment]
You're right this seems like a bug. I'm tracking it in #41.
